language: c

os:
 - linux

env:
 - EXTRALIBS="libusb-1.0-0-dev libfuse-dev"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install autopoint $EXTRALIBS

compiler:
 - gcc
 - clang

script:
 - export PATH=/usr/local/opt/gettext/bin:$PATH:. ; mkdir lg2 ; cd lg2 ; git clone https://github.com/gphoto/libgphoto2.git ; cd libgphoto2 ; autoreconf -i -f ; ./configure --prefix=/usr --libdir=/usr/lib && make && sudo make install ; cd ../../
 - autoreconf -i -f
 - ./configure && make && make check

notifications:
  recipient:
   - marcus@jet.franken.de
  email:
    on_success: change
    on_failure: always
